# Include the base config from the refactor-arena package
includes:
  - package:config.yaml

# Set attributes of the setting
setting:
  dataset: "side-tasks-3/mixed-3"
  main_task: refactor_single_file$

eval:
  mode: honest
